version: "3.9"
volumes:
  postgres_data:
  static:
services:
  db:
    image: postgres:13.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports: 
      - "5432:5432"

#  web:
#    image: fsow/foodgram_psql:v0.1.0
#    volumes:
#      - static:/code/static
#    restart: always
#    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
#    expose:
#      - "8000"
#    depends_on:
#      - db
#    env_file:
#      - ./.env
#  
#  nginx:
#    image: nginx:1.19.8-alpine
 #   volumes:
#      - static:/usr/share/nginx/html/static:ro
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
#    ports:
#      - "80:80"
#    depends_on:
#      - web

